### ISSUE TITLE
Update URL Whitelist

### ISSUE THREAD

**Issue by Asitt100** [walters954/why-salesforce#16]
It seems that the URL in Sandboxes has changed and is not included in "force.com" 
![image](https://github.com/walters954/why-salesforce/assets/155186069/8e8bf3e6-dc7b-428b-b3eb-c81978ef532f)
now i dont see the extension :(

**Comment by walters954** [comment]
@Asitt100 this should be resolved. Can you check.

**Comment by Asitt100** [comment]
Thank you!On Jun 28, 2024, at 10:45 AM, Warren Walters ***@***.***> wrote:﻿
@Asitt100 this should be resolved. Can you check.
